### ISSUE TITLE
DLL Injection not doing anything

### ISSUE THREAD

**Issue by fFukurou** [GameHackingAcademy/InternalMemoryHack#2]
Hey, first of all, thanks for the all great lessons!

So, I followed all the steps from the lesson, but on my actual machine, not a virtual machine.

1. Safe boot is off.
2. Have the exact same code from the github repo in my main.cpp file, and built it.
3. Added the path to AppInit_DLLs
4. Changed LoadAppInit_DLLs to 1
5. Restarted computer
6. Opened regedit again to make sure everything is correct
7. No luck :/ Pressing M doesn't change anything, not even using the MessageBox(0,0,0,0) function to test if it is working.

![image](https://github.com/user-attachments/assets/151d9d5c-e254-450a-ac0e-b4aa6709764a)

![image](https://github.com/user-attachments/assets/ecf5a5d7-a454-4009-8eb8-aed8e3e27c09)

Is this essential for future lessons? If not, I don't mind that it is not working, as long as I'm able to complete the course!

**Comment by attilathedud** [comment]
Sorry for the delay in the response and thanks for calling this out. It appears that Win11 x64 has some restrictions about injecting into x32 processes and AppInit_DLLs doesn't work anymore. I'll make a note in the lesson that the technique only works on Win10 and below.

In future lessons, it covers how to make a DLL injector, which sidesteps this issue entirely.
